import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../src/app/globals.css";
import Footer from "../components/footer";
import Header from "../components/header";
import Navigation from "../components/navigation";
import Prefooter from "../components/prefooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

        <Navigation />
        <Header />
        <main className="flex flex-col items-center justify-between min-h-screen p-24">
          <div className={inter.className}>
            {children}
          </div>
          <Prefooter />
        </main>
        <Footer />
      </body>
    </html>
  );
}
